version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 4s
      timeout: 4s
      retries: 10
      start_period: 2s

  server:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: "curl -f http://localhost:${PORT}"
      interval: 4s
      timeout: 4s
      retries: 10
      start_period: 2s
    depends_on:
      postgres:
        condition: service_healthy
